server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  zipkin:
    tracing:
      endpoint: http://zipkin2:9411
  tracing:
    sampling:
      probability: 1.0