server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://postgres:5432/customer
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  #  zipkin:
  #    baseurl: http://zipkin2:9411
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

management:
  #  zipkin:
  #    tracing:
  #      endpoint: http://zipkin2:9411
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans


