spring:
  application:
    name: eureka-server



server:
  port: 8761

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true

management:
  tracing:
    sampling:
      probability: 1.0
